In [1]:
%matplotlib inline
import pandas as pd
from pandas import DataFrame

## 加载数据

In [2]:
mobike_data = pd.read_csv("mobike_shanghai_sample_updated.csv")

## 评估

#### 可视化评估

In [3]:
mobike_data

,orderid,bikeid,userid,start_time,start_location_x,start_location_y,end_time,end_location_x,end_location_y,track
0,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,"121.347,31.392#121.348,31.389#121.349,31.390#1..."
1,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,"121.489,31.270#121.489,31.271#121.490,31.270#1..."
2,1106623,152045,8876,2016-08-13 16:17,121.383,31.254,2016-08-13 16:36,121.405,31.248,"121.381,31.251#121.382,31.251#121.382,31.252#1..."
3,1389484,196259,10648,2016-08-23 21:34,121.484,31.320,2016-08-23 21:43,121.471,31.325,"121.471,31.325#121.472,31.325#121.473,31.324#1..."
4,188537,78208,11735,2016-08-16 07:32,121.407,31.292,2016-08-16 07:41,121.418,31.288,"121.407,31.291#121.407,31.292#121.408,31.291#1..."
5,537030,66346,10335,2016-08-07 21:00,121.488,31.224,2016-08-07 21:20,121.468,31.233,"121.468,31.233#121.469,31.233#121.470,31.233#1..."
6,517706,99631,11258,2016-08-29 13:39,121.445,31.176,2016-08-29 13:54,121.447,31.192,"121.445,31.176#121.446,31.175#121.446,31.176#1..."
7,270836,63136,11361,2016-08-29 09:21,121.369,31.252,2016-08-29 13:43,121.376,31.233,"121.367,31.238#121.367,31.239#121.368,31.240#1..."
8,441362,331921,11705,2016-08-31 08:16,121.529,31.324,2016-08-31 08:19,121.532,31.323,"121.529,31.324#121.530,31.324#121.531,31.323#1..."
9,76435,347335,8135,2016-08-30 12:49,121.467,31.320,2016-08-30 13:03,121.447,31.318,"121.447,31.317#121.447,31.318#121.448,31.314#1..."
10,903987,13745,3117,2016-08-09 19:51,121.514,31.307,2016-08-09 19:59,121.510,31.304,"121.510,31.304#121.510,31.305#121.510,31.306#1..."
11,1749105,250190,8174,2016-08-26 17:57,121.385,31.166,2016-08-26 18:43,121.439,31.193,"121.384,31.166#121.385,31.166#121.386,31.166#1..."
12,760441,274835,17177,2016-08-31 09:53,121.419,31.292,2016-08-31 10:04,121.442,31.297,"121.419,31.292#121.420,31.292#121.420,31.293#1..."
13,163153,129925,9763,2016-08-09 08:33,121.551,31.279,2016-08-09 08:40,121.558,31.272,"121.551,31.278#121.551,31.279#121.552,31.277#1..."
14,1718308,291555,9867,2016-08-24 16:32,121.528,31.309,2016-08-24 16:45,121.523,31.321,"121.521,31.316#121.521,31.320#121.522,31.315#1..."
15,113197,277976,1499,2016-08-31 06:51,121.413,31.358,2016-08-31 07:08,121.432,31.356,"121.412,31.359#121.413,31.359#121.414,31.359#1..."
16,1660785,74378,3637,2016-08-06 22:30,121.590,31.243,2016-08-06 22:41,121.584,31.246,"121.585,31.246#121.586,31.245#121.586,31.246#1..."
17,1796188,210920,4156,2016-08-24 22:52,121.483,31.278,2016-08-24 23:02,121.473,31.273,"121.473,31.273#121.474,31.273#121.475,31.273#1..."
18,1725437,94034,10712,2016-08-31 21:31,121.442,31.264,2016-08-31 21:36,121.437,31.263,"121.437,31.262#121.437,31.263#121.438,31.261#1..."
19,974312,87103,4921,2016-08-08 17:31,121.437,31.294,2016-08-08 17:44,121.427,31.303,"121.427,31.303#121.428,31.303#121.429,31.298#1..."
20,1016344,319980,557,2016-08-29 20:20,121.466,31.185,2016-08-29 21:01,121.450,31.197,"121.450,31.196#121.450,31.197#121.451,31.195#1..."
21,4156,57862,2395,2016-08-09 02:34,121.384,31.188,2016-08-09 02:37,121.383,31.187,"121.383,31.187#121.383,31.188#121.384,31.188"
22,1013785,364751,14595,2016-08-30 12:17,121.388,31.268,2016-08-30 12:28,121.368,31.272,"121.368,31.272#121.369,31.272#121.369,31.273#1..."
23,420053,162491,13745,2016-08-20 14:25,121.432,31.180,2016-08-20 14:31,121.427,31.184,"121.426,31.182#121.427,31.182#121.427,31.183#1..."
24,737601,58198,6349,2016-08-01 17:57,121.513,31.302,2016-08-01 18:19,121.541,31.311,"121.513,31.302#121.513,31.303#121.514,31.302#1..."
25,1663013,9935,8929,2016-08-30 20:15,121.382,31.246,2016-08-30 20:22,121.380,31.251,"121.378,31.249#121.378,31.250#121.378,31.251#1..."
26,399789,292393,10700,2016-08-24 05:49,121.364,31.248,2016-08-24 05:58,121.367,31.237,"121.361,31.244#121.362,31.243#121.362,31.244#1..."
27,1399630,44728,5944,2016-08-22 18:27,121.506,31.329,2016-08-22 18:33,121.501,31.335,"121.499,31.336#121.499,31.337#121.500,31.336#1..."
28,773687,263024,15033,2016-08-24 07:45,121.464,31.193,2016-08-24 07:53,121.470,31.190,"121.464,31.192#121.464,31.193#121.465,31.192#1..."
29,466460,240822,12012,2016-08-21 22:13,121.533,31.318,2016-08-21 22:42,121.502,31.309,"121.502,31.308#121.502,31.309#121.503,31.308#1..."
...,...,...,...,...,...,...,...,...,...,...
102331,752209,264648,5474,2016-08-19 11:10,121.349,31.259,2016-08-19 11:16,121.354,31.261,"121.349,31.258#121.349,31.259#121.350,31.257#1..."
102332,1177538,94648,2319,2016-08-12 14:07,121.499,31.279,2016-08-12 14:11,121.502,31.275,"121.499,31.278#121.499,31.279#121.499,31.280#1..."
102333,194189,71476,7647,2016-08-10 08:47,121.403,31.130,2016-08-10 08:55,121.412,31.124,"121.402,31.128#121.402,31.129#121.403,31.127#1..."
102334,1612820,129498,9547,2016-08-06 19:21,121.501,31.275,2016-08-06 20:12,121.546,31.289,"121.501,31.275#121.502,31.275#121.503,31.276#1..."
102335,1676331,314831,15930,2016-08-28 20:23,121.460,31.328,2016-08-28 20:29,121.458,31.335,"121.458,31.335#121.459,31.328#121.459,31.329#1..."
102336,734652,333917,3905,2016-08-31 09:41,121.295,31.271,2016-08-31 09:53,121.304,31.272,"121.295,31.271#121.296,31.271#121.297,31.271#1..."
102337,947568,146806,9711,2016-08-27 14:47,121.495,31.170,2016-08-27 15:22,121.505,31.181,"121.494,31.170#121.494,31.171#121.494,31.177#1..."
102338,34563,203064,3038,2016-08-25 11:50,121.551,31.279,2016-08-25 11:55,121.554,31.273,"121.551,31.275#121.551,31.279#121.552,31.274#1..."
102339,375055,119804,6027,2016-08-01 11:27,121.532,31.315,2016-08-01 11:35,121.538,31.313,"121.532,31.314#121.532,31.315#121.533,31.314#1..."
102340,172833,66527,10097,2016-08-15 07:12,121.525,31.317,2016-08-15 07:19,121.531,31.321,"121.525,31.317#121.526,31.318#121.526,31.319#1..."
102341,405791,180713,5788,2016-08-20 14:01,121.405,31.235,2016-08-20 14:09,121.410,31.231,"121.404,31.232#121.405,31.231#121.405,31.232#1..."
102342,998890,175676,508,2016-08-23 13:14,121.432,31.259,2016-08-23 13:28,121.453,31.270,"121.432,31.259#121.433,31.259#121.434,31.259#1..."
102343,893197,214737,9990,2016-08-25 18:31,121.541,31.318,2016-08-25 18:39,121.532,31.314,"121.533,31.314#121.534,31.314#121.535,31.314#1..."
102344,1648715,11728,8836,2016-08-06 21:33,121.438,31.228,2016-08-06 21:40,121.430,31.234,"121.430,31.234#121.431,31.232#121.431,31.233#1..."
102345,48162,92143,3885,2016-08-08 00:19,121.436,31.320,2016-08-08 00:26,121.438,31.310,"121.436,31.318#121.436,31.319#121.436,31.320#1..."
102346,665032,6743,17715,2016-08-29 16:06,121.443,31.183,2016-08-29 16:08,121.441,31.178,"121.442,31.179#121.443,31.179#121.443,31.180#1..."
102347,1191602,301472,4041,2016-08-23 17:37,121.507,31.249,2016-08-23 17:58,121.515,31.269,"121.506,31.250#121.506,31.251#121.507,31.249#1..."
102348,1539900,185638,71,2016-08-31 18:09,121.422,31.171,2016-08-31 18:19,121.425,31.163,"121.421,31.171#121.422,31.171#121.423,31.171#1..."
102349,1449488,349625,414,2016-08-27 19:39,121.451,31.279,2016-08-27 20:17,121.425,31.295,"121.425,31.295#121.426,31.295#121.427,31.295#1..."
102350,1303672,80655,7520,2016-08-17 17:16,121.532,31.331,2016-08-17 17:22,121.531,31.323,"121.528,31.331#121.531,31.328#121.532,31.324#1..."
102351,657156,59970,5497,2016-08-31 09:09,121.372,31.119,2016-08-31 09:23,121.375,31.107,"121.372,31.118#121.372,31.119#121.373,31.117#1..."
102352,186351,24298,11196,2016-08-11 07:42,121.422,31.201,2016-08-11 07:46,121.420,31.197,"121.419,31.200#121.419,31.201#121.420,31.199#1..."
102353,1168582,322536,15738,2016-08-26 09:03,121.473,31.193,2016-08-26 09:10,121.471,31.202,"121.473,31.193#121.473,31.194#121.473,31.196#1..."
102354,182261,16353,2628,2016-08-03 10:05,121.498,31.288,2016-08-03 10:13,121.508,31.281,"121.498,31.287#121.498,31.288#121.499,31.287#1..."
102355,640008,329621,10791,2016-08-29 15:39,121.518,31.311,2016-08-29 15:48,121.523,31.322,"121.518,31.311#121.519,31.311#121.519,31.312#1..."
102356,1479550,214335,1423,2016-08-28 18:03,121.478,31.297,2016-08-28 18:09,121.481,31.304,"121.478,31.297#121.479,31.297#121.480,31.297#1..."
102357,1478273,160487,3067,2016-08-14 20:22,121.320,31.238,2016-08-14 20:28,121.312,31.235,"121.312,31.235#121.313,31.235#121.313,31.236#1..."
102358,367733,179530,12746,2016-08-27 09:54,121.391,31.307,2016-08-27 10:06,121.398,31.306,"121.390,31.307#121.391,31.307#121.392,31.307#1..."
102359,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,"121.510,31.272#121.510,31.273#121.511,31.273#1..."
102360,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,"121.518,31.274#121.519,31.270#121.519,31.271#1..."

#### 编程评估

In [4]:
mobike_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102361 entries, 0 to 102360
Data columns (total 10 columns):
orderid             102361 non-null int64
bikeid              102361 non-null int64
userid              102361 non-null int64
start_time          102361 non-null object
start_location_x    102361 non-null float64
start_location_y    102361 non-null float64
end_time            102361 non-null object
end_location_x      102361 non-null float64
end_location_y      102361 non-null float64
track               102361 non-null object
dtypes: float64(4), int64(3), object(3)
memory usage: 7.8+ MB

In [5]:
mobike_data.describe()

,orderid,bikeid,userid,start_location_x,start_location_y,end_location_x,end_location_y
count,1.023610e+05,102361.000000,102361.000000,102361.000000,102361.000000,102361.000000,102361.000000
mean,8.940838e+05,155425.868690,7834.435644,121.454144,31.251740,121.453736,31.252029
std,5.219651e+05,98816.625402,4530.387938,0.060862,0.057358,0.061577,0.057740
min,6.000000e+00,3.000000,1.000000,121.173000,30.842000,120.486000,30.841000
25%,4.386790e+05,74701.000000,4095.000000,121.415000,31.212000,121.414000,31.212000
50%,8.901510e+05,141990.000000,7617.000000,121.456000,31.260000,121.456000,31.261000
75%,1.343252e+06,228303.000000,11278.000000,121.497000,31.294000,121.497000,31.294000
max,1.807864e+06,387351.000000,17753.000000,121.970000,31.450000,121.971000,31.477000

In [6]:
mobike_data[mobike_data.orderid.duplicated()]

Empty DataFrame
Columns: [orderid, bikeid, userid, start_time, start_location_x, start_location_y, end_time, end_location_x, end_location_y, track]
Index: []

In [7]:
mobike_data.track

0         121.347,31.392#121.348,31.389#121.349,31.390#1...
1         121.489,31.270#121.489,31.271#121.490,31.270#1...
2         121.381,31.251#121.382,31.251#121.382,31.252#1...
3         121.471,31.325#121.472,31.325#121.473,31.324#1...
4         121.407,31.291#121.407,31.292#121.408,31.291#1...
5         121.468,31.233#121.469,31.233#121.470,31.233#1...
6         121.445,31.176#121.446,31.175#121.446,31.176#1...
7         121.367,31.238#121.367,31.239#121.368,31.240#1...
8         121.529,31.324#121.530,31.324#121.531,31.323#1...
9         121.447,31.317#121.447,31.318#121.448,31.314#1...
10        121.510,31.304#121.510,31.305#121.510,31.306#1...
11        121.384,31.166#121.385,31.166#121.386,31.166#1...
12        121.419,31.292#121.420,31.292#121.420,31.293#1...
13        121.551,31.278#121.551,31.279#121.552,31.277#1...
14        121.521,31.316#121.521,31.320#121.522,31.315#1...
15        121.412,31.359#121.413,31.359#121.414,31.359#1...
16        121.585,31.246#121.586,31.245#121.586,31.246#1...
17        121.473,31.273#121.474,31.273#121.475,31.273#1...
18        121.437,31.262#121.437,31.263#121.438,31.261#1...
19        121.427,31.303#121.428,31.303#121.429,31.298#1...
20        121.450,31.196#121.450,31.197#121.451,31.195#1...
21             121.383,31.187#121.383,31.188#121.384,31.188
22        121.368,31.272#121.369,31.272#121.369,31.273#1...
23        121.426,31.182#121.427,31.182#121.427,31.183#1...
24        121.513,31.302#121.513,31.303#121.514,31.302#1...
25        121.378,31.249#121.378,31.250#121.378,31.251#1...
26        121.361,31.244#121.362,31.243#121.362,31.244#1...
27        121.499,31.336#121.499,31.337#121.500,31.336#1...
28        121.464,31.192#121.464,31.193#121.465,31.192#1...
29        121.502,31.308#121.502,31.309#121.503,31.308#1...
                                ...
102331    121.349,31.258#121.349,31.259#121.350,31.257#1...
102332    121.499,31.278#121.499,31.279#121.499,31.280#1...
102333    121.402,31.128#121.402,31.129#121.403,31.127#1...
102334    121.501,31.275#121.502,31.275#121.503,31.276#1...
102335    121.458,31.335#121.459,31.328#121.459,31.329#1...
102336    121.295,31.271#121.296,31.271#121.297,31.271#1...
102337    121.494,31.170#121.494,31.171#121.494,31.177#1...
102338    121.551,31.275#121.551,31.279#121.552,31.274#1...
102339    121.532,31.314#121.532,31.315#121.533,31.314#1...
102340    121.525,31.317#121.526,31.318#121.526,31.319#1...
102341    121.404,31.232#121.405,31.231#121.405,31.232#1...
102342    121.432,31.259#121.433,31.259#121.434,31.259#1...
102343    121.533,31.314#121.534,31.314#121.535,31.314#1...
102344    121.430,31.234#121.431,31.232#121.431,31.233#1...
102345    121.436,31.318#121.436,31.319#121.436,31.320#1...
102346    121.442,31.179#121.443,31.179#121.443,31.180#1...
102347    121.506,31.250#121.506,31.251#121.507,31.249#1...
102348    121.421,31.171#121.422,31.171#121.423,31.171#1...
102349    121.425,31.295#121.426,31.295#121.427,31.295#1...
102350    121.528,31.331#121.531,31.328#121.532,31.324#1...
102351    121.372,31.118#121.372,31.119#121.373,31.117#1...
102352    121.419,31.200#121.419,31.201#121.420,31.199#1...
102353    121.473,31.193#121.473,31.194#121.473,31.196#1...
102354    121.498,31.287#121.498,31.288#121.499,31.287#1...
102355    121.518,31.311#121.519,31.311#121.519,31.312#1...
102356    121.478,31.297#121.479,31.297#121.480,31.297#1...
102357    121.312,31.235#121.313,31.235#121.313,31.236#1...
102358    121.390,31.307#121.391,31.307#121.392,31.307#1...
102359    121.510,31.272#121.510,31.273#121.511,31.273#1...
102360    121.518,31.274#121.519,31.270#121.519,31.271#1...
Name: track, Length: 102361, dtype: object

## 质量
- 错误的数据类型（start_time，end_time）

## 清洁度
- track应该分成多个位置信息

## 清理

In [68]:
mobike_data_clean = mobike_data.copy()

### 清洁度

#### track应该分成多个位置信息

##### 定义
使用split方法将track划分为track_location_x,track_location_y。

##### 代码

In [69]:
mobike_data_clean.track = mobike_data_clean.track.str.split('#')

In [70]:
orderid_list = []
track_x = []
track_y = []

for index in mobike_data_clean.index:
    for element in mobike_data_clean.track.loc[index]:
        temp_x, temp_y = element.split(',')
        orderid_list.append(mobike_data_clean.orderid.loc[index]) 
        track_x.append(temp_x)
        track_y.append(temp_y)

In [71]:
data = {"orderid": orderid_list, "track_x": track_x, "track_y": track_y}
track_data = DataFrame(data)

In [72]:
mobike_data_clean = pd.merge(mobike_data_clean, track_data)
mobike_data_clean = mobike_data_clean.drop("track", axis = 1)

ValueError: could not convert string to float: '31.29\\'

In [73]:
mobike_data_clean

,orderid,bikeid,userid,start_time,start_location_x,start_location_y,end_time,end_location_x,end_location_y,track_x,track_y
0,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.347,31.392
1,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.348,31.389
2,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.349,31.390
3,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.350,31.390
4,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.351,31.390
5,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.351,31.391
6,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.352,31.391
7,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.353,31.391
8,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.353,31.394
9,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.354,31.391
10,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.355,31.391
11,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.356,31.389
12,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.356,31.390
13,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.356,31.391
14,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.357,31.388
15,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.357,31.389
16,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.489,31.270
17,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.489,31.271
18,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.490,31.270
19,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.490,31.271
20,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.491,31.271
21,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.492,31.270
22,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.492,31.271
23,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.493,31.269
24,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.493,31.270
25,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.494,31.268
26,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.494,31.269
27,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.495,31.269
28,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.495,31.270
29,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.496,31.270
...,...,...,...,...,...,...,...,...,...,...,...
2381075,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.511,31.273
2381076,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.512,31.271
2381077,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.512,31.272
2381078,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.512,31.273
2381079,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.513,31.270
2381080,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.513,31.271
2381081,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.514,31.269
2381082,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.514,31.270
2381083,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.515,31.269
2381084,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.518,31.274
2381085,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.519,31.270
2381086,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.519,31.271
2381087,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.519,31.272
2381088,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.519,31.273
2381089,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.519,31.274
2381090,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.520,31.264
2381091,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.520,31.265
2381092,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.520,31.268
2381093,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.520,31.269
2381094,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.520,31.270
2381095,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.521,31.261
2381096,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.521,31.262
2381097,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.521,31.263
2381098,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.521,31.264
2381099,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.521,31.265
2381100,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.521,31.266
2381101,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.521,31.267
2381102,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.521,31.268
2381103,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.522,31.262
2381104,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.522,31.266

In [161]:
mobike_data_clean.track_y = mobike_data_clean.track_y.str.extract('(\d{2}\.\d{1,3})' ,expand=True)

In [162]:
mobike_data_clean.track_x = mobike_data_clean.track_x.astype('float')
mobike_data_clean.track_y = mobike_data_clean.track_y.astype('float')

##### 测试

In [163]:
mobike_data_clean

,orderid,bikeid,userid,start_time,start_location_x,start_location_y,end_time,end_location_x,end_location_y,track_x,track_y
0,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.347,31.392
1,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.348,31.389
2,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.349,31.390
3,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.350,31.390
4,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.351,31.390
5,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.351,31.391
6,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.352,31.391
7,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.353,31.391
8,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.353,31.394
9,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.354,31.391
10,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.355,31.391
11,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.356,31.389
12,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.356,31.390
13,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.356,31.391
14,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.357,31.388
15,78387,158357,10080,2016-08-20 06:57,121.348,31.389,2016-08-20 07:04,121.357,31.388,121.357,31.389
16,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.489,31.270
17,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.489,31.271
18,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.490,31.270
19,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.490,31.271
20,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.491,31.271
21,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.492,31.270
22,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.492,31.271
23,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.493,31.269
24,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.493,31.270
25,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.494,31.268
26,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.494,31.269
27,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.495,31.269
28,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.495,31.270
29,891333,92776,6605,2016-08-29 19:09,121.508,31.279,2016-08-29 19:31,121.489,31.271,121.496,31.270
...,...,...,...,...,...,...,...,...,...,...,...
2381075,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.511,31.273
2381076,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.512,31.271
2381077,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.512,31.272
2381078,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.512,31.273
2381079,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.513,31.270
2381080,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.513,31.271
2381081,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.514,31.269
2381082,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.514,31.270
2381083,64915,167419,837,2016-08-20 06:04,121.515,31.269,2016-08-20 06:10,121.510,31.272,121.515,31.269
2381084,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.518,31.274
2381085,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.519,31.270
2381086,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.519,31.271
2381087,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.519,31.272
2381088,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.519,31.273
2381089,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.519,31.274
2381090,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.520,31.264
2381091,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.520,31.265
2381092,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.520,31.268
2381093,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.520,31.269
2381094,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.520,31.270
2381095,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.521,31.261
2381096,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.521,31.262
2381097,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.521,31.263
2381098,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.521,31.264
2381099,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.521,31.265
2381100,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.521,31.266
2381101,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.521,31.267
2381102,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.521,31.268
2381103,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.522,31.262
2381104,326987,63172,2547,2016-08-09 10:51,121.521,31.261,2016-08-09 11:01,121.518,31.274,121.522,31.266

In [164]:
mobike_data_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2381105 entries, 0 to 2381104
Data columns (total 11 columns):
orderid             int64
bikeid              int64
userid              int64
start_time          object
start_location_x    float64
start_location_y    float64
end_time            object
end_location_x      float64
end_location_y      float64
track_x             float64
track_y             float64
dtypes: float64(6), int64(3), object(2)
memory usage: 298.0+ MB

### 质量

#### 错误的数据类型（start_time，end_time）

##### 定义
利用to_datatime方法将start_time和end_time转为date_time格式

##### 代码

In [165]:
mobike_data_clean.start_time = pd.to_datetime(mobike_data_clean.start_time)
mobike_data_clean.end_time = pd.to_datetime(mobike_data_clean.end_time)

##### 测试

In [166]:
mobike_data_clean.head(10)

,orderid,bikeid,userid,start_time,start_location_x,start_location_y,end_time,end_location_x,end_location_y,track_x,track_y
0,78387,158357,10080,2016-08-20 06:57:00,121.348,31.389,2016-08-20 07:04:00,121.357,31.388,121.347,31.392
1,78387,158357,10080,2016-08-20 06:57:00,121.348,31.389,2016-08-20 07:04:00,121.357,31.388,121.348,31.389
2,78387,158357,10080,2016-08-20 06:57:00,121.348,31.389,2016-08-20 07:04:00,121.357,31.388,121.349,31.390
3,78387,158357,10080,2016-08-20 06:57:00,121.348,31.389,2016-08-20 07:04:00,121.357,31.388,121.350,31.390
4,78387,158357,10080,2016-08-20 06:57:00,121.348,31.389,2016-08-20 07:04:00,121.357,31.388,121.351,31.390
5,78387,158357,10080,2016-08-20 06:57:00,121.348,31.389,2016-08-20 07:04:00,121.357,31.388,121.351,31.391
6,78387,158357,10080,2016-08-20 06:57:00,121.348,31.389,2016-08-20 07:04:00,121.357,31.388,121.352,31.391
7,78387,158357,10080,2016-08-20 06:57:00,121.348,31.389,2016-08-20 07:04:00,121.357,31.388,121.353,31.391
8,78387,158357,10080,2016-08-20 06:57:00,121.348,31.389,2016-08-20 07:04:00,121.357,31.388,121.353,31.394
9,78387,158357,10080,2016-08-20 06:57:00,121.348,31.389,2016-08-20 07:04:00,121.357,31.388,121.354,31.391

In [167]:
mobike_data_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2381105 entries, 0 to 2381104
Data columns (total 11 columns):
orderid             int64
bikeid              int64
userid              int64
start_time          datetime64[ns]
start_location_x    float64
start_location_y    float64
end_time            datetime64[ns]
end_location_x      float64
end_location_y      float64
track_x             float64
track_y             float64
dtypes: datetime64[ns](2), float64(6), int64(3)
memory usage: 298.0 MB

## 保存数据

In [168]:
save_file_name = 'mobike_shanghai_sample_clean.csv'
mobike_data_clean.to_csv(save_file_name, encoding='utf-8',index=False)